
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'AND COMMA CONFLICT ENGAGES ID INHERITS LBRACE PERMISSION PERMISSIONS RBRACE ROLE SEMI USERpolicy : statement_liststatement_list : statement statement_liststatement_list : statementstatement : role_def\n| perm_def\n| user_def\n| sod_defperm_def : PERMISSION ID SEMIrole_def : ROLE ID LBRACE role_body RBRACErole_body : role_attr role_bodyrole_body : role_attr : INHERITS id_list SEMIrole_attr : PERMISSIONS id_list SEMIuser_def : USER ID ENGAGES id_list SEMIsod_def : CONFLICT ID AND ID SEMIid_list : ID COMMA id_listid_list : ID'
    
_lr_action_items = {'ROLE':([0,3,4,5,6,7,18,28,33,34,],[8,8,-4,-5,-6,-7,-8,-9,-14,-15,]),'PERMISSION':([0,3,4,5,6,7,18,28,33,34,],[9,9,-4,-5,-6,-7,-8,-9,-14,-15,]),'USER':([0,3,4,5,6,7,18,28,33,34,],[10,10,-4,-5,-6,-7,-8,-9,-14,-15,]),'CONFLICT':([0,3,4,5,6,7,18,28,33,34,],[11,11,-4,-5,-6,-7,-8,-9,-14,-15,]),'$end':([1,2,3,4,5,6,7,12,18,28,33,34,],[0,-1,-3,-4,-5,-6,-7,-2,-8,-9,-14,-15,]),'ID':([8,9,10,11,19,20,23,24,32,],[13,14,15,16,25,27,25,25,25,]),'LBRACE':([13,],[17,]),'SEMI':([14,25,26,27,30,31,37,],[18,-17,33,34,35,36,-16,]),'ENGAGES':([15,],[19,]),'AND':([16,],[20,]),'RBRACE':([17,21,22,29,35,36,],[-11,28,-11,-10,-12,-13,]),'INHERITS':([17,22,35,36,],[23,23,-12,-13,]),'PERMISSIONS':([17,22,35,36,],[24,24,-12,-13,]),'COMMA':([25,],[32,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'policy':([0,],[1,]),'statement_list':([0,3,],[2,12,]),'statement':([0,3,],[3,3,]),'role_def':([0,3,],[4,4,]),'perm_def':([0,3,],[5,5,]),'user_def':([0,3,],[6,6,]),'sod_def':([0,3,],[7,7,]),'role_body':([17,22,],[21,29,]),'role_attr':([17,22,],[22,22,]),'id_list':([19,23,24,32,],[26,30,31,37,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> policy","S'",1,None,None,None),
  ('policy -> statement_list','policy',1,'p_policy','parser.py',8),
  ('statement_list -> statement statement_list','statement_list',2,'p_statement_list_multiple','parser.py',12),
  ('statement_list -> statement','statement_list',1,'p_statement_list_single','parser.py',16),
  ('statement -> role_def','statement',1,'p_statement','parser.py',20),
  ('statement -> perm_def','statement',1,'p_statement','parser.py',21),
  ('statement -> user_def','statement',1,'p_statement','parser.py',22),
  ('statement -> sod_def','statement',1,'p_statement','parser.py',23),
  ('perm_def -> PERMISSION ID SEMI','perm_def',3,'p_perm_def','parser.py',28),
  ('role_def -> ROLE ID LBRACE role_body RBRACE','role_def',5,'p_role_def','parser.py',33),
  ('role_body -> role_attr role_body','role_body',2,'p_role_body_recur','parser.py',49),
  ('role_body -> <empty>','role_body',0,'p_role_body_empty','parser.py',56),
  ('role_attr -> INHERITS id_list SEMI','role_attr',3,'p_role_attr_inherits','parser.py',60),
  ('role_attr -> PERMISSIONS id_list SEMI','role_attr',3,'p_role_attr_permissions','parser.py',64),
  ('user_def -> USER ID ENGAGES id_list SEMI','user_def',5,'p_user_def','parser.py',69),
  ('sod_def -> CONFLICT ID AND ID SEMI','sod_def',5,'p_sod_def','parser.py',74),
  ('id_list -> ID COMMA id_list','id_list',3,'p_id_list_multi','parser.py',79),
  ('id_list -> ID','id_list',1,'p_id_list_single','parser.py',83),
]
