"""
report_generator.py  -  Week 11: Security Analysis Report Generator
=====================================================================
Takes the integrated output of the RBAC Compiler (CompilerResult) and
generates a structured, human-readable Markdown report, complete with
Mermaid.js charts for role hierarchy visualization.

Usage (from the project root):
    python src/report_generator.py <policy_file.rbac> [--out <output_report.md>]
"""

from __future__ import annotations
import sys
import os
import datetime

# Ensure src/ is on the module search path
_SRC = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, _SRC)

from rbac_compiler import RBACCompiler, CompilerResult
from conflict_detector import ConflictReport
from escalation_detector import EscalationReport

class ReportGenerator:
    """Generates Markdown reports from a CompilerResult."""
    
    def __init__(self, policy_name: str, result: CompilerResult):
        self.policy_name = policy_name
        self.result = result

    def generate_markdown(self) -> str:
        """Generates the full Markdown report as a string."""
        now = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        
        md = [
            f"# Security Analysis Report",
            f"**Policy File:** `{self.policy_name}`  ",
            f"**Generated:** {now}  ",
            f"**Status:** {'❌ FOUND ISSUES' if self.result.total_issues > 0 else '✅ CLEAN'}",
            "",
            "---",
            ""
        ]

        if not self.result.parse_ok:
            md.extend([
                "## ❌ Parsing Error",
                "The policy failed lexical or syntax analysis. Cannot proceed with security checks.",
                ""
            ])
            return "\n".join(md)

        if self.result.semantic_errors:
            md.extend([
                "## ❌ Semantic Errors",
                "The following critical semantic errors were found:"
            ])
            for err in self.result.semantic_errors:
                md.append(f"- {err}")
            md.append("")

        # Section: Role Hierarchy (Mermaid JS)
        md.extend(self._generate_hierarchy_section())

        # Section: Conflicts
        if self.result.conflict_report:
            md.extend(self._generate_conflict_section())
        else:
            md.extend(["## Conflict Detection", "*(Analysis did not run)*", ""])

        # Section: Privilege Escalation
        if self.result.escalation_report:
            md.extend(self._generate_escalation_section())
        else:
            md.extend(["## Privilege Escalation Detection", "*(Analysis did not run)*", ""])

        # Footer
        md.extend([
            "---",
            f"*Report computationally generated by the RBAC Policy DSL Compiler (Week 11).*  ",
            f"**Total Issues Detected:** {self.result.total_issues}"
        ])

        return "\n".join(md)

    def _generate_hierarchy_section(self) -> list[str]:
        md = ["## Level 1: Role Hierarchy Visualization\n"]
        e_report = self.result.escalation_report
        if not e_report or not getattr(e_report, 'graph_edges', None):
            md.append("*No inheritance relationships found in this policy.*\n")
            return md

        edges = e_report.graph_edges
        md.extend([
            "```mermaid",
            "graph BT",
            "    %% BT = Bottom-Top (Children point to Parents)"
        ])
        for child, parent in sorted(edges):
            md.append(f"    {child} -->|inherits| {parent}")
        md.extend([
            "```\n"
        ])
        return md

    def _generate_conflict_section(self) -> list[str]:
        c_report = self.result.conflict_report
        md = ["## Level 2: Separation of Duty & Conflicts\n"]
        
        if c_report.errors:
            md.append("### ❌ Structural Errors")
            for e in c_report.errors:
                md.append(f"- {e}")
            md.append("")

        if c_report.conflicts:
            md.append("### ⚡ Separation of Duty Violations")
            for c in c_report.conflicts:
                md.append(f"- **VIOLATION:** {c}")
            md.append("")
        else:
            md.append("✅ *No Separation of Duty conflicts detected.*\n")

        if c_report.warnings:
            md.append("### ⚠️ Warnings (Redundancy)")
            for w in c_report.warnings:
                md.append(f"- {w}")
            md.append("")
        
        return md

    def _generate_escalation_section(self) -> list[str]:
        e_report = self.result.escalation_report
        md = ["## Level 3: Privilege Escalation & Dangerous Actions\n"]

        if e_report.escalation_paths:
            md.append(f"### ⬆️ Escalation Paths ({len(e_report.escalation_paths)} found)")
            md.append("| From Role | To Role | Path | Gained Permissions |")
            md.append("|---|---|---|---|")
            for ep in e_report.escalation_paths:
                path_str = " -> ".join(ep.path)
                perms_str = ", ".join(ep.gained_perms) if ep.gained_perms else "*(all parent perms)*"
                md.append(f"| `{ep.from_role}` | `{ep.to_role}` | `{path_str}` | `{perms_str}` |")
            md.append("")
        else:
            md.append("✅ *No standard escalation paths detected.*\n")

        if e_report.dangerous_combos_found:
            md.append(f"### ☢️ Dangerous Permission Combinations ({len(e_report.dangerous_combos_found)} found)")
            for d in e_report.dangerous_combos_found:
                md.append(f"- {d}")
            md.append("")
        else:
            md.append("✅ *No dangerous combinations detected.*\n")

        if e_report.warnings:
            md.extend(["### ⚠️ Additional Warnings", ""])
            for w in e_report.warnings:
                md.append(f"- {w}")
            md.append("")

        return md


def main():
    if hasattr(sys.stdout, 'reconfigure'):
        sys.stdout.reconfigure(encoding='utf-8')
    if len(sys.argv) < 2:
        print("Usage: python src/report_generator.py <policy_file.rbac> [--out <output_report.md>]")
        sys.exit(1)

    policy_path = sys.argv[1]
    
    out_file = None
    if len(sys.argv) == 4 and sys.argv[2] == "--out":
        out_file = sys.argv[3]
    elif len(sys.argv) > 2:
        print("Usage: python src/report_generator.py <policy_file.rbac> [--out <output_report.md>]")
        sys.exit(1)

    if not os.path.isfile(policy_path):
        print("Error: File not found - " + policy_path)
        sys.exit(1)

    with open(policy_path, "r", encoding="utf-8") as fh:
        source = fh.read()

    # We want to run quietly, so we'll suppress stdout from the compiler
    old_stdout = sys.stdout
    with open(os.devnull, 'w', encoding='utf-8') as fnull:
        sys.stdout = fnull
        compiler = RBACCompiler()
        result = compiler.compile(source)
    sys.stdout = old_stdout

    policy_name = os.path.basename(policy_path)
    generator = ReportGenerator(policy_name, result)
    markdown_report = generator.generate_markdown()

    if out_file:
        # Create dir if not exists
        out_dir = os.path.dirname(out_file)
        if out_dir and not os.path.exists(out_dir):
            os.makedirs(out_dir)
            
        with open(out_file, "w", encoding="utf-8") as fw:
            fw.write(markdown_report)
        print(f"[OK] Report generated successfully at: {out_file}")
    else:
        print(markdown_report)

if __name__ == "__main__":
    main()
